// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPVjoJ34PIw6zONrWTdXv-ci2kMyFhdno',
    appId: '1:297453730074:web:f79fc9364f30444f13d4a3',
    messagingSenderId: '297453730074',
    projectId: 'whatsapp-7151d',
    authDomain: 'whatsapp-7151d.firebaseapp.com',
    databaseURL: 'https://whatsapp-7151d-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-7151d.appspot.com',
    measurementId: 'G-J2YKWG2VHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcjrOivG1kUOS3_zBZtDO14TuD7m2DKwA',
    appId: '1:297453730074:android:59e90c8d554c8fa913d4a3',
    messagingSenderId: '297453730074',
    projectId: 'whatsapp-7151d',
    databaseURL: 'https://whatsapp-7151d-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-7151d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDym-L8Zi5UFIKx5DQDkr15tcOeXVqWqs8',
    appId: '1:297453730074:ios:e3d9d1e43d5251f613d4a3',
    messagingSenderId: '297453730074',
    projectId: 'whatsapp-7151d',
    databaseURL: 'https://whatsapp-7151d-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-7151d.appspot.com',
    iosClientId: '297453730074-1qa9qhimcn5jv3s3te431t5uvalmfhlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDym-L8Zi5UFIKx5DQDkr15tcOeXVqWqs8',
    appId: '1:297453730074:ios:ca80149e0d47345e13d4a3',
    messagingSenderId: '297453730074',
    projectId: 'whatsapp-7151d',
    databaseURL: 'https://whatsapp-7151d-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-7151d.appspot.com',
    iosClientId: '297453730074-hcbvejbqji56ldujm9v2a4914hpcb4ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
